// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package subscription

import (
	"context"

	"github.com/GenesisEducationKyiv/software-engineering-school-5-0-denyshuzovskyi/nimbus-lib/pkg/notification/command"
	"github.com/GenesisEducationKyiv/software-engineering-school-5-0-denyshuzovskyi/weather-upd-subscription-srv/internal/dto"
	"github.com/GenesisEducationKyiv/software-engineering-school-5-0-denyshuzovskyi/weather-upd-subscription-srv/internal/lib/sqlutil"
	"github.com/GenesisEducationKyiv/software-engineering-school-5-0-denyshuzovskyi/weather-upd-subscription-srv/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWeatherProvider creates a new instance of MockWeatherProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWeatherProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWeatherProvider {
	mock := &MockWeatherProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWeatherProvider is an autogenerated mock type for the WeatherProvider type
type MockWeatherProvider struct {
	mock.Mock
}

type MockWeatherProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWeatherProvider) EXPECT() *MockWeatherProvider_Expecter {
	return &MockWeatherProvider_Expecter{mock: &_m.Mock}
}

// GetCurrentWeather provides a mock function for the type MockWeatherProvider
func (_mock *MockWeatherProvider) GetCurrentWeather(context1 context.Context, s string) (*dto.WeatherWithLocationDTO, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentWeather")
	}

	var r0 *dto.WeatherWithLocationDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*dto.WeatherWithLocationDTO, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *dto.WeatherWithLocationDTO); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.WeatherWithLocationDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWeatherProvider_GetCurrentWeather_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentWeather'
type MockWeatherProvider_GetCurrentWeather_Call struct {
	*mock.Call
}

// GetCurrentWeather is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockWeatherProvider_Expecter) GetCurrentWeather(context1 interface{}, s interface{}) *MockWeatherProvider_GetCurrentWeather_Call {
	return &MockWeatherProvider_GetCurrentWeather_Call{Call: _e.mock.On("GetCurrentWeather", context1, s)}
}

func (_c *MockWeatherProvider_GetCurrentWeather_Call) Run(run func(context1 context.Context, s string)) *MockWeatherProvider_GetCurrentWeather_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWeatherProvider_GetCurrentWeather_Call) Return(weatherWithLocationDTO *dto.WeatherWithLocationDTO, err error) *MockWeatherProvider_GetCurrentWeather_Call {
	_c.Call.Return(weatherWithLocationDTO, err)
	return _c
}

func (_c *MockWeatherProvider_GetCurrentWeather_Call) RunAndReturn(run func(context1 context.Context, s string) (*dto.WeatherWithLocationDTO, error)) *MockWeatherProvider_GetCurrentWeather_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSubscriberRepository creates a new instance of MockSubscriberRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubscriberRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubscriberRepository {
	mock := &MockSubscriberRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSubscriberRepository is an autogenerated mock type for the SubscriberRepository type
type MockSubscriberRepository struct {
	mock.Mock
}

type MockSubscriberRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubscriberRepository) EXPECT() *MockSubscriberRepository_Expecter {
	return &MockSubscriberRepository_Expecter{mock: &_m.Mock}
}

// FindByEmail provides a mock function for the type MockSubscriberRepository
func (_mock *MockSubscriberRepository) FindByEmail(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, s string) (*model.Subscriber, error) {
	ret := _mock.Called(context1, sQLExecutor, s)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *model.Subscriber
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlutil.SQLExecutor, string) (*model.Subscriber, error)); ok {
		return returnFunc(context1, sQLExecutor, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlutil.SQLExecutor, string) *model.Subscriber); ok {
		r0 = returnFunc(context1, sQLExecutor, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Subscriber)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlutil.SQLExecutor, string) error); ok {
		r1 = returnFunc(context1, sQLExecutor, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubscriberRepository_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockSubscriberRepository_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - context1 context.Context
//   - sQLExecutor sqlutil.SQLExecutor
//   - s string
func (_e *MockSubscriberRepository_Expecter) FindByEmail(context1 interface{}, sQLExecutor interface{}, s interface{}) *MockSubscriberRepository_FindByEmail_Call {
	return &MockSubscriberRepository_FindByEmail_Call{Call: _e.mock.On("FindByEmail", context1, sQLExecutor, s)}
}

func (_c *MockSubscriberRepository_FindByEmail_Call) Run(run func(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, s string)) *MockSubscriberRepository_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlutil.SQLExecutor
		if args[1] != nil {
			arg1 = args[1].(sqlutil.SQLExecutor)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSubscriberRepository_FindByEmail_Call) Return(subscriber *model.Subscriber, err error) *MockSubscriberRepository_FindByEmail_Call {
	_c.Call.Return(subscriber, err)
	return _c
}

func (_c *MockSubscriberRepository_FindByEmail_Call) RunAndReturn(run func(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, s string) (*model.Subscriber, error)) *MockSubscriberRepository_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindById provides a mock function for the type MockSubscriberRepository
func (_mock *MockSubscriberRepository) FindById(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, n int32) (*model.Subscriber, error) {
	ret := _mock.Called(context1, sQLExecutor, n)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 *model.Subscriber
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlutil.SQLExecutor, int32) (*model.Subscriber, error)); ok {
		return returnFunc(context1, sQLExecutor, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlutil.SQLExecutor, int32) *model.Subscriber); ok {
		r0 = returnFunc(context1, sQLExecutor, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Subscriber)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlutil.SQLExecutor, int32) error); ok {
		r1 = returnFunc(context1, sQLExecutor, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubscriberRepository_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type MockSubscriberRepository_FindById_Call struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - context1 context.Context
//   - sQLExecutor sqlutil.SQLExecutor
//   - n int32
func (_e *MockSubscriberRepository_Expecter) FindById(context1 interface{}, sQLExecutor interface{}, n interface{}) *MockSubscriberRepository_FindById_Call {
	return &MockSubscriberRepository_FindById_Call{Call: _e.mock.On("FindById", context1, sQLExecutor, n)}
}

func (_c *MockSubscriberRepository_FindById_Call) Run(run func(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, n int32)) *MockSubscriberRepository_FindById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlutil.SQLExecutor
		if args[1] != nil {
			arg1 = args[1].(sqlutil.SQLExecutor)
		}
		var arg2 int32
		if args[2] != nil {
			arg2 = args[2].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSubscriberRepository_FindById_Call) Return(subscriber *model.Subscriber, err error) *MockSubscriberRepository_FindById_Call {
	_c.Call.Return(subscriber, err)
	return _c
}

func (_c *MockSubscriberRepository_FindById_Call) RunAndReturn(run func(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, n int32) (*model.Subscriber, error)) *MockSubscriberRepository_FindById_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockSubscriberRepository
func (_mock *MockSubscriberRepository) Save(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, subscriber *model.Subscriber) (int32, error) {
	ret := _mock.Called(context1, sQLExecutor, subscriber)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 int32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlutil.SQLExecutor, *model.Subscriber) (int32, error)); ok {
		return returnFunc(context1, sQLExecutor, subscriber)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlutil.SQLExecutor, *model.Subscriber) int32); ok {
		r0 = returnFunc(context1, sQLExecutor, subscriber)
	} else {
		r0 = ret.Get(0).(int32)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlutil.SQLExecutor, *model.Subscriber) error); ok {
		r1 = returnFunc(context1, sQLExecutor, subscriber)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubscriberRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockSubscriberRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - context1 context.Context
//   - sQLExecutor sqlutil.SQLExecutor
//   - subscriber *model.Subscriber
func (_e *MockSubscriberRepository_Expecter) Save(context1 interface{}, sQLExecutor interface{}, subscriber interface{}) *MockSubscriberRepository_Save_Call {
	return &MockSubscriberRepository_Save_Call{Call: _e.mock.On("Save", context1, sQLExecutor, subscriber)}
}

func (_c *MockSubscriberRepository_Save_Call) Run(run func(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, subscriber *model.Subscriber)) *MockSubscriberRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlutil.SQLExecutor
		if args[1] != nil {
			arg1 = args[1].(sqlutil.SQLExecutor)
		}
		var arg2 *model.Subscriber
		if args[2] != nil {
			arg2 = args[2].(*model.Subscriber)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSubscriberRepository_Save_Call) Return(n int32, err error) *MockSubscriberRepository_Save_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSubscriberRepository_Save_Call) RunAndReturn(run func(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, subscriber *model.Subscriber) (int32, error)) *MockSubscriberRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSubscriptionRepository creates a new instance of MockSubscriptionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubscriptionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubscriptionRepository {
	mock := &MockSubscriptionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSubscriptionRepository is an autogenerated mock type for the SubscriptionRepository type
type MockSubscriptionRepository struct {
	mock.Mock
}

type MockSubscriptionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubscriptionRepository) EXPECT() *MockSubscriptionRepository_Expecter {
	return &MockSubscriptionRepository_Expecter{mock: &_m.Mock}
}

// DeleteById provides a mock function for the type MockSubscriptionRepository
func (_mock *MockSubscriptionRepository) DeleteById(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, n int32) error {
	ret := _mock.Called(context1, sQLExecutor, n)

	if len(ret) == 0 {
		panic("no return value specified for DeleteById")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlutil.SQLExecutor, int32) error); ok {
		r0 = returnFunc(context1, sQLExecutor, n)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSubscriptionRepository_DeleteById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteById'
type MockSubscriptionRepository_DeleteById_Call struct {
	*mock.Call
}

// DeleteById is a helper method to define mock.On call
//   - context1 context.Context
//   - sQLExecutor sqlutil.SQLExecutor
//   - n int32
func (_e *MockSubscriptionRepository_Expecter) DeleteById(context1 interface{}, sQLExecutor interface{}, n interface{}) *MockSubscriptionRepository_DeleteById_Call {
	return &MockSubscriptionRepository_DeleteById_Call{Call: _e.mock.On("DeleteById", context1, sQLExecutor, n)}
}

func (_c *MockSubscriptionRepository_DeleteById_Call) Run(run func(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, n int32)) *MockSubscriptionRepository_DeleteById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlutil.SQLExecutor
		if args[1] != nil {
			arg1 = args[1].(sqlutil.SQLExecutor)
		}
		var arg2 int32
		if args[2] != nil {
			arg2 = args[2].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSubscriptionRepository_DeleteById_Call) Return(err error) *MockSubscriptionRepository_DeleteById_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSubscriptionRepository_DeleteById_Call) RunAndReturn(run func(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, n int32) error) *MockSubscriptionRepository_DeleteById_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllByFrequencyAndConfirmedStatus provides a mock function for the type MockSubscriptionRepository
func (_mock *MockSubscriptionRepository) FindAllByFrequencyAndConfirmedStatus(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, frequency model.Frequency) ([]*model.Subscription, error) {
	ret := _mock.Called(context1, sQLExecutor, frequency)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByFrequencyAndConfirmedStatus")
	}

	var r0 []*model.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlutil.SQLExecutor, model.Frequency) ([]*model.Subscription, error)); ok {
		return returnFunc(context1, sQLExecutor, frequency)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlutil.SQLExecutor, model.Frequency) []*model.Subscription); ok {
		r0 = returnFunc(context1, sQLExecutor, frequency)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlutil.SQLExecutor, model.Frequency) error); ok {
		r1 = returnFunc(context1, sQLExecutor, frequency)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubscriptionRepository_FindAllByFrequencyAndConfirmedStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllByFrequencyAndConfirmedStatus'
type MockSubscriptionRepository_FindAllByFrequencyAndConfirmedStatus_Call struct {
	*mock.Call
}

// FindAllByFrequencyAndConfirmedStatus is a helper method to define mock.On call
//   - context1 context.Context
//   - sQLExecutor sqlutil.SQLExecutor
//   - frequency model.Frequency
func (_e *MockSubscriptionRepository_Expecter) FindAllByFrequencyAndConfirmedStatus(context1 interface{}, sQLExecutor interface{}, frequency interface{}) *MockSubscriptionRepository_FindAllByFrequencyAndConfirmedStatus_Call {
	return &MockSubscriptionRepository_FindAllByFrequencyAndConfirmedStatus_Call{Call: _e.mock.On("FindAllByFrequencyAndConfirmedStatus", context1, sQLExecutor, frequency)}
}

func (_c *MockSubscriptionRepository_FindAllByFrequencyAndConfirmedStatus_Call) Run(run func(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, frequency model.Frequency)) *MockSubscriptionRepository_FindAllByFrequencyAndConfirmedStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlutil.SQLExecutor
		if args[1] != nil {
			arg1 = args[1].(sqlutil.SQLExecutor)
		}
		var arg2 model.Frequency
		if args[2] != nil {
			arg2 = args[2].(model.Frequency)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSubscriptionRepository_FindAllByFrequencyAndConfirmedStatus_Call) Return(subscriptions []*model.Subscription, err error) *MockSubscriptionRepository_FindAllByFrequencyAndConfirmedStatus_Call {
	_c.Call.Return(subscriptions, err)
	return _c
}

func (_c *MockSubscriptionRepository_FindAllByFrequencyAndConfirmedStatus_Call) RunAndReturn(run func(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, frequency model.Frequency) ([]*model.Subscription, error)) *MockSubscriptionRepository_FindAllByFrequencyAndConfirmedStatus_Call {
	_c.Call.Return(run)
	return _c
}

// FindById provides a mock function for the type MockSubscriptionRepository
func (_mock *MockSubscriptionRepository) FindById(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, n int32) (*model.Subscription, error) {
	ret := _mock.Called(context1, sQLExecutor, n)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 *model.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlutil.SQLExecutor, int32) (*model.Subscription, error)); ok {
		return returnFunc(context1, sQLExecutor, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlutil.SQLExecutor, int32) *model.Subscription); ok {
		r0 = returnFunc(context1, sQLExecutor, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlutil.SQLExecutor, int32) error); ok {
		r1 = returnFunc(context1, sQLExecutor, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubscriptionRepository_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type MockSubscriptionRepository_FindById_Call struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - context1 context.Context
//   - sQLExecutor sqlutil.SQLExecutor
//   - n int32
func (_e *MockSubscriptionRepository_Expecter) FindById(context1 interface{}, sQLExecutor interface{}, n interface{}) *MockSubscriptionRepository_FindById_Call {
	return &MockSubscriptionRepository_FindById_Call{Call: _e.mock.On("FindById", context1, sQLExecutor, n)}
}

func (_c *MockSubscriptionRepository_FindById_Call) Run(run func(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, n int32)) *MockSubscriptionRepository_FindById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlutil.SQLExecutor
		if args[1] != nil {
			arg1 = args[1].(sqlutil.SQLExecutor)
		}
		var arg2 int32
		if args[2] != nil {
			arg2 = args[2].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSubscriptionRepository_FindById_Call) Return(subscription *model.Subscription, err error) *MockSubscriptionRepository_FindById_Call {
	_c.Call.Return(subscription, err)
	return _c
}

func (_c *MockSubscriptionRepository_FindById_Call) RunAndReturn(run func(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, n int32) (*model.Subscription, error)) *MockSubscriptionRepository_FindById_Call {
	_c.Call.Return(run)
	return _c
}

// FindBySubscriberIdAndLocationName provides a mock function for the type MockSubscriptionRepository
func (_mock *MockSubscriptionRepository) FindBySubscriberIdAndLocationName(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, n int32, s string) (*model.Subscription, error) {
	ret := _mock.Called(context1, sQLExecutor, n, s)

	if len(ret) == 0 {
		panic("no return value specified for FindBySubscriberIdAndLocationName")
	}

	var r0 *model.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlutil.SQLExecutor, int32, string) (*model.Subscription, error)); ok {
		return returnFunc(context1, sQLExecutor, n, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlutil.SQLExecutor, int32, string) *model.Subscription); ok {
		r0 = returnFunc(context1, sQLExecutor, n, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlutil.SQLExecutor, int32, string) error); ok {
		r1 = returnFunc(context1, sQLExecutor, n, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubscriptionRepository_FindBySubscriberIdAndLocationName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySubscriberIdAndLocationName'
type MockSubscriptionRepository_FindBySubscriberIdAndLocationName_Call struct {
	*mock.Call
}

// FindBySubscriberIdAndLocationName is a helper method to define mock.On call
//   - context1 context.Context
//   - sQLExecutor sqlutil.SQLExecutor
//   - n int32
//   - s string
func (_e *MockSubscriptionRepository_Expecter) FindBySubscriberIdAndLocationName(context1 interface{}, sQLExecutor interface{}, n interface{}, s interface{}) *MockSubscriptionRepository_FindBySubscriberIdAndLocationName_Call {
	return &MockSubscriptionRepository_FindBySubscriberIdAndLocationName_Call{Call: _e.mock.On("FindBySubscriberIdAndLocationName", context1, sQLExecutor, n, s)}
}

func (_c *MockSubscriptionRepository_FindBySubscriberIdAndLocationName_Call) Run(run func(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, n int32, s string)) *MockSubscriptionRepository_FindBySubscriberIdAndLocationName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlutil.SQLExecutor
		if args[1] != nil {
			arg1 = args[1].(sqlutil.SQLExecutor)
		}
		var arg2 int32
		if args[2] != nil {
			arg2 = args[2].(int32)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSubscriptionRepository_FindBySubscriberIdAndLocationName_Call) Return(subscription *model.Subscription, err error) *MockSubscriptionRepository_FindBySubscriberIdAndLocationName_Call {
	_c.Call.Return(subscription, err)
	return _c
}

func (_c *MockSubscriptionRepository_FindBySubscriberIdAndLocationName_Call) RunAndReturn(run func(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, n int32, s string) (*model.Subscription, error)) *MockSubscriptionRepository_FindBySubscriberIdAndLocationName_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockSubscriptionRepository
func (_mock *MockSubscriptionRepository) Save(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, subscription *model.Subscription) (int32, error) {
	ret := _mock.Called(context1, sQLExecutor, subscription)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 int32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlutil.SQLExecutor, *model.Subscription) (int32, error)); ok {
		return returnFunc(context1, sQLExecutor, subscription)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlutil.SQLExecutor, *model.Subscription) int32); ok {
		r0 = returnFunc(context1, sQLExecutor, subscription)
	} else {
		r0 = ret.Get(0).(int32)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlutil.SQLExecutor, *model.Subscription) error); ok {
		r1 = returnFunc(context1, sQLExecutor, subscription)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubscriptionRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockSubscriptionRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - context1 context.Context
//   - sQLExecutor sqlutil.SQLExecutor
//   - subscription *model.Subscription
func (_e *MockSubscriptionRepository_Expecter) Save(context1 interface{}, sQLExecutor interface{}, subscription interface{}) *MockSubscriptionRepository_Save_Call {
	return &MockSubscriptionRepository_Save_Call{Call: _e.mock.On("Save", context1, sQLExecutor, subscription)}
}

func (_c *MockSubscriptionRepository_Save_Call) Run(run func(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, subscription *model.Subscription)) *MockSubscriptionRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlutil.SQLExecutor
		if args[1] != nil {
			arg1 = args[1].(sqlutil.SQLExecutor)
		}
		var arg2 *model.Subscription
		if args[2] != nil {
			arg2 = args[2].(*model.Subscription)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSubscriptionRepository_Save_Call) Return(n int32, err error) *MockSubscriptionRepository_Save_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSubscriptionRepository_Save_Call) RunAndReturn(run func(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, subscription *model.Subscription) (int32, error)) *MockSubscriptionRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockSubscriptionRepository
func (_mock *MockSubscriptionRepository) Update(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, subscription *model.Subscription) (*model.Subscription, error) {
	ret := _mock.Called(context1, sQLExecutor, subscription)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlutil.SQLExecutor, *model.Subscription) (*model.Subscription, error)); ok {
		return returnFunc(context1, sQLExecutor, subscription)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlutil.SQLExecutor, *model.Subscription) *model.Subscription); ok {
		r0 = returnFunc(context1, sQLExecutor, subscription)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlutil.SQLExecutor, *model.Subscription) error); ok {
		r1 = returnFunc(context1, sQLExecutor, subscription)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubscriptionRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSubscriptionRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - context1 context.Context
//   - sQLExecutor sqlutil.SQLExecutor
//   - subscription *model.Subscription
func (_e *MockSubscriptionRepository_Expecter) Update(context1 interface{}, sQLExecutor interface{}, subscription interface{}) *MockSubscriptionRepository_Update_Call {
	return &MockSubscriptionRepository_Update_Call{Call: _e.mock.On("Update", context1, sQLExecutor, subscription)}
}

func (_c *MockSubscriptionRepository_Update_Call) Run(run func(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, subscription *model.Subscription)) *MockSubscriptionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlutil.SQLExecutor
		if args[1] != nil {
			arg1 = args[1].(sqlutil.SQLExecutor)
		}
		var arg2 *model.Subscription
		if args[2] != nil {
			arg2 = args[2].(*model.Subscription)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSubscriptionRepository_Update_Call) Return(subscription1 *model.Subscription, err error) *MockSubscriptionRepository_Update_Call {
	_c.Call.Return(subscription1, err)
	return _c
}

func (_c *MockSubscriptionRepository_Update_Call) RunAndReturn(run func(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, subscription *model.Subscription) (*model.Subscription, error)) *MockSubscriptionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenRepository creates a new instance of MockTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenRepository {
	mock := &MockTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenRepository is an autogenerated mock type for the TokenRepository type
type MockTokenRepository struct {
	mock.Mock
}

type MockTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenRepository) EXPECT() *MockTokenRepository_Expecter {
	return &MockTokenRepository_Expecter{mock: &_m.Mock}
}

// FindBySubscriptionIdAndType provides a mock function for the type MockTokenRepository
func (_mock *MockTokenRepository) FindBySubscriptionIdAndType(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, n int32, tokenType model.TokenType) (*model.Token, error) {
	ret := _mock.Called(context1, sQLExecutor, n, tokenType)

	if len(ret) == 0 {
		panic("no return value specified for FindBySubscriptionIdAndType")
	}

	var r0 *model.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlutil.SQLExecutor, int32, model.TokenType) (*model.Token, error)); ok {
		return returnFunc(context1, sQLExecutor, n, tokenType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlutil.SQLExecutor, int32, model.TokenType) *model.Token); ok {
		r0 = returnFunc(context1, sQLExecutor, n, tokenType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlutil.SQLExecutor, int32, model.TokenType) error); ok {
		r1 = returnFunc(context1, sQLExecutor, n, tokenType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenRepository_FindBySubscriptionIdAndType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySubscriptionIdAndType'
type MockTokenRepository_FindBySubscriptionIdAndType_Call struct {
	*mock.Call
}

// FindBySubscriptionIdAndType is a helper method to define mock.On call
//   - context1 context.Context
//   - sQLExecutor sqlutil.SQLExecutor
//   - n int32
//   - tokenType model.TokenType
func (_e *MockTokenRepository_Expecter) FindBySubscriptionIdAndType(context1 interface{}, sQLExecutor interface{}, n interface{}, tokenType interface{}) *MockTokenRepository_FindBySubscriptionIdAndType_Call {
	return &MockTokenRepository_FindBySubscriptionIdAndType_Call{Call: _e.mock.On("FindBySubscriptionIdAndType", context1, sQLExecutor, n, tokenType)}
}

func (_c *MockTokenRepository_FindBySubscriptionIdAndType_Call) Run(run func(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, n int32, tokenType model.TokenType)) *MockTokenRepository_FindBySubscriptionIdAndType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlutil.SQLExecutor
		if args[1] != nil {
			arg1 = args[1].(sqlutil.SQLExecutor)
		}
		var arg2 int32
		if args[2] != nil {
			arg2 = args[2].(int32)
		}
		var arg3 model.TokenType
		if args[3] != nil {
			arg3 = args[3].(model.TokenType)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTokenRepository_FindBySubscriptionIdAndType_Call) Return(token *model.Token, err error) *MockTokenRepository_FindBySubscriptionIdAndType_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockTokenRepository_FindBySubscriptionIdAndType_Call) RunAndReturn(run func(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, n int32, tokenType model.TokenType) (*model.Token, error)) *MockTokenRepository_FindBySubscriptionIdAndType_Call {
	_c.Call.Return(run)
	return _c
}

// FindByToken provides a mock function for the type MockTokenRepository
func (_mock *MockTokenRepository) FindByToken(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, s string) (*model.Token, error) {
	ret := _mock.Called(context1, sQLExecutor, s)

	if len(ret) == 0 {
		panic("no return value specified for FindByToken")
	}

	var r0 *model.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlutil.SQLExecutor, string) (*model.Token, error)); ok {
		return returnFunc(context1, sQLExecutor, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlutil.SQLExecutor, string) *model.Token); ok {
		r0 = returnFunc(context1, sQLExecutor, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlutil.SQLExecutor, string) error); ok {
		r1 = returnFunc(context1, sQLExecutor, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenRepository_FindByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByToken'
type MockTokenRepository_FindByToken_Call struct {
	*mock.Call
}

// FindByToken is a helper method to define mock.On call
//   - context1 context.Context
//   - sQLExecutor sqlutil.SQLExecutor
//   - s string
func (_e *MockTokenRepository_Expecter) FindByToken(context1 interface{}, sQLExecutor interface{}, s interface{}) *MockTokenRepository_FindByToken_Call {
	return &MockTokenRepository_FindByToken_Call{Call: _e.mock.On("FindByToken", context1, sQLExecutor, s)}
}

func (_c *MockTokenRepository_FindByToken_Call) Run(run func(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, s string)) *MockTokenRepository_FindByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlutil.SQLExecutor
		if args[1] != nil {
			arg1 = args[1].(sqlutil.SQLExecutor)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTokenRepository_FindByToken_Call) Return(token *model.Token, err error) *MockTokenRepository_FindByToken_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockTokenRepository_FindByToken_Call) RunAndReturn(run func(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, s string) (*model.Token, error)) *MockTokenRepository_FindByToken_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockTokenRepository
func (_mock *MockTokenRepository) Save(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, token *model.Token) error {
	ret := _mock.Called(context1, sQLExecutor, token)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlutil.SQLExecutor, *model.Token) error); ok {
		r0 = returnFunc(context1, sQLExecutor, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockTokenRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - context1 context.Context
//   - sQLExecutor sqlutil.SQLExecutor
//   - token *model.Token
func (_e *MockTokenRepository_Expecter) Save(context1 interface{}, sQLExecutor interface{}, token interface{}) *MockTokenRepository_Save_Call {
	return &MockTokenRepository_Save_Call{Call: _e.mock.On("Save", context1, sQLExecutor, token)}
}

func (_c *MockTokenRepository_Save_Call) Run(run func(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, token *model.Token)) *MockTokenRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlutil.SQLExecutor
		if args[1] != nil {
			arg1 = args[1].(sqlutil.SQLExecutor)
		}
		var arg2 *model.Token
		if args[2] != nil {
			arg2 = args[2].(*model.Token)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTokenRepository_Save_Call) Return(err error) *MockTokenRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenRepository_Save_Call) RunAndReturn(run func(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, token *model.Token) error) *MockTokenRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNotificationSender creates a new instance of MockNotificationSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationSender {
	mock := &MockNotificationSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotificationSender is an autogenerated mock type for the NotificationSender type
type MockNotificationSender struct {
	mock.Mock
}

type MockNotificationSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationSender) EXPECT() *MockNotificationSender_Expecter {
	return &MockNotificationSender_Expecter{mock: &_m.Mock}
}

// SendConfirmation provides a mock function for the type MockNotificationSender
func (_mock *MockNotificationSender) SendConfirmation(context1 context.Context, sendConfirmation command.SendConfirmation) error {
	ret := _mock.Called(context1, sendConfirmation)

	if len(ret) == 0 {
		panic("no return value specified for SendConfirmation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, command.SendConfirmation) error); ok {
		r0 = returnFunc(context1, sendConfirmation)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotificationSender_SendConfirmation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendConfirmation'
type MockNotificationSender_SendConfirmation_Call struct {
	*mock.Call
}

// SendConfirmation is a helper method to define mock.On call
//   - context1 context.Context
//   - sendConfirmation command.SendConfirmation
func (_e *MockNotificationSender_Expecter) SendConfirmation(context1 interface{}, sendConfirmation interface{}) *MockNotificationSender_SendConfirmation_Call {
	return &MockNotificationSender_SendConfirmation_Call{Call: _e.mock.On("SendConfirmation", context1, sendConfirmation)}
}

func (_c *MockNotificationSender_SendConfirmation_Call) Run(run func(context1 context.Context, sendConfirmation command.SendConfirmation)) *MockNotificationSender_SendConfirmation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 command.SendConfirmation
		if args[1] != nil {
			arg1 = args[1].(command.SendConfirmation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotificationSender_SendConfirmation_Call) Return(err error) *MockNotificationSender_SendConfirmation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotificationSender_SendConfirmation_Call) RunAndReturn(run func(context1 context.Context, sendConfirmation command.SendConfirmation) error) *MockNotificationSender_SendConfirmation_Call {
	_c.Call.Return(run)
	return _c
}

// SendConfirmationSuccess provides a mock function for the type MockNotificationSender
func (_mock *MockNotificationSender) SendConfirmationSuccess(context1 context.Context, sendConfirmationSuccess command.SendConfirmationSuccess) error {
	ret := _mock.Called(context1, sendConfirmationSuccess)

	if len(ret) == 0 {
		panic("no return value specified for SendConfirmationSuccess")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, command.SendConfirmationSuccess) error); ok {
		r0 = returnFunc(context1, sendConfirmationSuccess)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotificationSender_SendConfirmationSuccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendConfirmationSuccess'
type MockNotificationSender_SendConfirmationSuccess_Call struct {
	*mock.Call
}

// SendConfirmationSuccess is a helper method to define mock.On call
//   - context1 context.Context
//   - sendConfirmationSuccess command.SendConfirmationSuccess
func (_e *MockNotificationSender_Expecter) SendConfirmationSuccess(context1 interface{}, sendConfirmationSuccess interface{}) *MockNotificationSender_SendConfirmationSuccess_Call {
	return &MockNotificationSender_SendConfirmationSuccess_Call{Call: _e.mock.On("SendConfirmationSuccess", context1, sendConfirmationSuccess)}
}

func (_c *MockNotificationSender_SendConfirmationSuccess_Call) Run(run func(context1 context.Context, sendConfirmationSuccess command.SendConfirmationSuccess)) *MockNotificationSender_SendConfirmationSuccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 command.SendConfirmationSuccess
		if args[1] != nil {
			arg1 = args[1].(command.SendConfirmationSuccess)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotificationSender_SendConfirmationSuccess_Call) Return(err error) *MockNotificationSender_SendConfirmationSuccess_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotificationSender_SendConfirmationSuccess_Call) RunAndReturn(run func(context1 context.Context, sendConfirmationSuccess command.SendConfirmationSuccess) error) *MockNotificationSender_SendConfirmationSuccess_Call {
	_c.Call.Return(run)
	return _c
}

// SendUnsubscribeSuccess provides a mock function for the type MockNotificationSender
func (_mock *MockNotificationSender) SendUnsubscribeSuccess(context1 context.Context, sendUnsubscribeSuccess command.SendUnsubscribeSuccess) error {
	ret := _mock.Called(context1, sendUnsubscribeSuccess)

	if len(ret) == 0 {
		panic("no return value specified for SendUnsubscribeSuccess")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, command.SendUnsubscribeSuccess) error); ok {
		r0 = returnFunc(context1, sendUnsubscribeSuccess)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotificationSender_SendUnsubscribeSuccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendUnsubscribeSuccess'
type MockNotificationSender_SendUnsubscribeSuccess_Call struct {
	*mock.Call
}

// SendUnsubscribeSuccess is a helper method to define mock.On call
//   - context1 context.Context
//   - sendUnsubscribeSuccess command.SendUnsubscribeSuccess
func (_e *MockNotificationSender_Expecter) SendUnsubscribeSuccess(context1 interface{}, sendUnsubscribeSuccess interface{}) *MockNotificationSender_SendUnsubscribeSuccess_Call {
	return &MockNotificationSender_SendUnsubscribeSuccess_Call{Call: _e.mock.On("SendUnsubscribeSuccess", context1, sendUnsubscribeSuccess)}
}

func (_c *MockNotificationSender_SendUnsubscribeSuccess_Call) Run(run func(context1 context.Context, sendUnsubscribeSuccess command.SendUnsubscribeSuccess)) *MockNotificationSender_SendUnsubscribeSuccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 command.SendUnsubscribeSuccess
		if args[1] != nil {
			arg1 = args[1].(command.SendUnsubscribeSuccess)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotificationSender_SendUnsubscribeSuccess_Call) Return(err error) *MockNotificationSender_SendUnsubscribeSuccess_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotificationSender_SendUnsubscribeSuccess_Call) RunAndReturn(run func(context1 context.Context, sendUnsubscribeSuccess command.SendUnsubscribeSuccess) error) *MockNotificationSender_SendUnsubscribeSuccess_Call {
	_c.Call.Return(run)
	return _c
}
