// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package notification

import (
	"context"

	"github.com/GenesisEducationKyiv/software-engineering-school-5-0-denyshuzovskyi/nimbus-lib/pkg/notification/command"
	mock "github.com/stretchr/testify/mock"
)

// NewMockNotificationSender creates a new instance of MockNotificationSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationSender {
	mock := &MockNotificationSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotificationSender is an autogenerated mock type for the NotificationSender type
type MockNotificationSender struct {
	mock.Mock
}

type MockNotificationSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationSender) EXPECT() *MockNotificationSender_Expecter {
	return &MockNotificationSender_Expecter{mock: &_m.Mock}
}

// SendWeatherUpdate provides a mock function for the type MockNotificationSender
func (_mock *MockNotificationSender) SendWeatherUpdate(context1 context.Context, sendWeatherUpdate command.SendWeatherUpdate) error {
	ret := _mock.Called(context1, sendWeatherUpdate)

	if len(ret) == 0 {
		panic("no return value specified for SendWeatherUpdate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, command.SendWeatherUpdate) error); ok {
		r0 = returnFunc(context1, sendWeatherUpdate)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotificationSender_SendWeatherUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendWeatherUpdate'
type MockNotificationSender_SendWeatherUpdate_Call struct {
	*mock.Call
}

// SendWeatherUpdate is a helper method to define mock.On call
//   - context1 context.Context
//   - sendWeatherUpdate command.SendWeatherUpdate
func (_e *MockNotificationSender_Expecter) SendWeatherUpdate(context1 interface{}, sendWeatherUpdate interface{}) *MockNotificationSender_SendWeatherUpdate_Call {
	return &MockNotificationSender_SendWeatherUpdate_Call{Call: _e.mock.On("SendWeatherUpdate", context1, sendWeatherUpdate)}
}

func (_c *MockNotificationSender_SendWeatherUpdate_Call) Run(run func(context1 context.Context, sendWeatherUpdate command.SendWeatherUpdate)) *MockNotificationSender_SendWeatherUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 command.SendWeatherUpdate
		if args[1] != nil {
			arg1 = args[1].(command.SendWeatherUpdate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotificationSender_SendWeatherUpdate_Call) Return(err error) *MockNotificationSender_SendWeatherUpdate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotificationSender_SendWeatherUpdate_Call) RunAndReturn(run func(context1 context.Context, sendWeatherUpdate command.SendWeatherUpdate) error) *MockNotificationSender_SendWeatherUpdate_Call {
	_c.Call.Return(run)
	return _c
}
