// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package subscription

import (
	"context"

	"github.com/GenesisEducationKyiv/software-engineering-school-5-0-denyshuzovskyi/internal/dto"
	"github.com/GenesisEducationKyiv/software-engineering-school-5-0-denyshuzovskyi/internal/lib/sqlutil"
	"github.com/GenesisEducationKyiv/software-engineering-school-5-0-denyshuzovskyi/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWeatherProvider creates a new instance of MockWeatherProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWeatherProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWeatherProvider {
	mock := &MockWeatherProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWeatherProvider is an autogenerated mock type for the WeatherProvider type
type MockWeatherProvider struct {
	mock.Mock
}

type MockWeatherProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWeatherProvider) EXPECT() *MockWeatherProvider_Expecter {
	return &MockWeatherProvider_Expecter{mock: &_m.Mock}
}

// GetCurrentWeather provides a mock function for the type MockWeatherProvider
func (_mock *MockWeatherProvider) GetCurrentWeather(context1 context.Context, s string) (*model.Weather, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentWeather")
	}

	var r0 *model.Weather
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Weather, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Weather); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Weather)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWeatherProvider_GetCurrentWeather_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentWeather'
type MockWeatherProvider_GetCurrentWeather_Call struct {
	*mock.Call
}

// GetCurrentWeather is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockWeatherProvider_Expecter) GetCurrentWeather(context1 interface{}, s interface{}) *MockWeatherProvider_GetCurrentWeather_Call {
	return &MockWeatherProvider_GetCurrentWeather_Call{Call: _e.mock.On("GetCurrentWeather", context1, s)}
}

func (_c *MockWeatherProvider_GetCurrentWeather_Call) Run(run func(context1 context.Context, s string)) *MockWeatherProvider_GetCurrentWeather_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWeatherProvider_GetCurrentWeather_Call) Return(weather *model.Weather, err error) *MockWeatherProvider_GetCurrentWeather_Call {
	_c.Call.Return(weather, err)
	return _c
}

func (_c *MockWeatherProvider_GetCurrentWeather_Call) RunAndReturn(run func(context1 context.Context, s string) (*model.Weather, error)) *MockWeatherProvider_GetCurrentWeather_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSubscriberRepository creates a new instance of MockSubscriberRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubscriberRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubscriberRepository {
	mock := &MockSubscriberRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSubscriberRepository is an autogenerated mock type for the SubscriberRepository type
type MockSubscriberRepository struct {
	mock.Mock
}

type MockSubscriberRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubscriberRepository) EXPECT() *MockSubscriberRepository_Expecter {
	return &MockSubscriberRepository_Expecter{mock: &_m.Mock}
}

// FindByEmail provides a mock function for the type MockSubscriberRepository
func (_mock *MockSubscriberRepository) FindByEmail(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, s string) (*model.Subscriber, error) {
	ret := _mock.Called(context1, sQLExecutor, s)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *model.Subscriber
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlutil.SQLExecutor, string) (*model.Subscriber, error)); ok {
		return returnFunc(context1, sQLExecutor, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlutil.SQLExecutor, string) *model.Subscriber); ok {
		r0 = returnFunc(context1, sQLExecutor, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Subscriber)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlutil.SQLExecutor, string) error); ok {
		r1 = returnFunc(context1, sQLExecutor, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubscriberRepository_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockSubscriberRepository_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - context1 context.Context
//   - sQLExecutor sqlutil.SQLExecutor
//   - s string
func (_e *MockSubscriberRepository_Expecter) FindByEmail(context1 interface{}, sQLExecutor interface{}, s interface{}) *MockSubscriberRepository_FindByEmail_Call {
	return &MockSubscriberRepository_FindByEmail_Call{Call: _e.mock.On("FindByEmail", context1, sQLExecutor, s)}
}

func (_c *MockSubscriberRepository_FindByEmail_Call) Run(run func(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, s string)) *MockSubscriberRepository_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlutil.SQLExecutor
		if args[1] != nil {
			arg1 = args[1].(sqlutil.SQLExecutor)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSubscriberRepository_FindByEmail_Call) Return(subscriber *model.Subscriber, err error) *MockSubscriberRepository_FindByEmail_Call {
	_c.Call.Return(subscriber, err)
	return _c
}

func (_c *MockSubscriberRepository_FindByEmail_Call) RunAndReturn(run func(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, s string) (*model.Subscriber, error)) *MockSubscriberRepository_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindById provides a mock function for the type MockSubscriberRepository
func (_mock *MockSubscriberRepository) FindById(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, n int32) (*model.Subscriber, error) {
	ret := _mock.Called(context1, sQLExecutor, n)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 *model.Subscriber
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlutil.SQLExecutor, int32) (*model.Subscriber, error)); ok {
		return returnFunc(context1, sQLExecutor, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlutil.SQLExecutor, int32) *model.Subscriber); ok {
		r0 = returnFunc(context1, sQLExecutor, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Subscriber)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlutil.SQLExecutor, int32) error); ok {
		r1 = returnFunc(context1, sQLExecutor, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubscriberRepository_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type MockSubscriberRepository_FindById_Call struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - context1 context.Context
//   - sQLExecutor sqlutil.SQLExecutor
//   - n int32
func (_e *MockSubscriberRepository_Expecter) FindById(context1 interface{}, sQLExecutor interface{}, n interface{}) *MockSubscriberRepository_FindById_Call {
	return &MockSubscriberRepository_FindById_Call{Call: _e.mock.On("FindById", context1, sQLExecutor, n)}
}

func (_c *MockSubscriberRepository_FindById_Call) Run(run func(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, n int32)) *MockSubscriberRepository_FindById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlutil.SQLExecutor
		if args[1] != nil {
			arg1 = args[1].(sqlutil.SQLExecutor)
		}
		var arg2 int32
		if args[2] != nil {
			arg2 = args[2].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSubscriberRepository_FindById_Call) Return(subscriber *model.Subscriber, err error) *MockSubscriberRepository_FindById_Call {
	_c.Call.Return(subscriber, err)
	return _c
}

func (_c *MockSubscriberRepository_FindById_Call) RunAndReturn(run func(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, n int32) (*model.Subscriber, error)) *MockSubscriberRepository_FindById_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockSubscriberRepository
func (_mock *MockSubscriberRepository) Save(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, subscriber *model.Subscriber) (int32, error) {
	ret := _mock.Called(context1, sQLExecutor, subscriber)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 int32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlutil.SQLExecutor, *model.Subscriber) (int32, error)); ok {
		return returnFunc(context1, sQLExecutor, subscriber)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlutil.SQLExecutor, *model.Subscriber) int32); ok {
		r0 = returnFunc(context1, sQLExecutor, subscriber)
	} else {
		r0 = ret.Get(0).(int32)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlutil.SQLExecutor, *model.Subscriber) error); ok {
		r1 = returnFunc(context1, sQLExecutor, subscriber)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubscriberRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockSubscriberRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - context1 context.Context
//   - sQLExecutor sqlutil.SQLExecutor
//   - subscriber *model.Subscriber
func (_e *MockSubscriberRepository_Expecter) Save(context1 interface{}, sQLExecutor interface{}, subscriber interface{}) *MockSubscriberRepository_Save_Call {
	return &MockSubscriberRepository_Save_Call{Call: _e.mock.On("Save", context1, sQLExecutor, subscriber)}
}

func (_c *MockSubscriberRepository_Save_Call) Run(run func(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, subscriber *model.Subscriber)) *MockSubscriberRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlutil.SQLExecutor
		if args[1] != nil {
			arg1 = args[1].(sqlutil.SQLExecutor)
		}
		var arg2 *model.Subscriber
		if args[2] != nil {
			arg2 = args[2].(*model.Subscriber)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSubscriberRepository_Save_Call) Return(n int32, err error) *MockSubscriberRepository_Save_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSubscriberRepository_Save_Call) RunAndReturn(run func(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, subscriber *model.Subscriber) (int32, error)) *MockSubscriberRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSubscriptionRepository creates a new instance of MockSubscriptionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubscriptionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubscriptionRepository {
	mock := &MockSubscriptionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSubscriptionRepository is an autogenerated mock type for the SubscriptionRepository type
type MockSubscriptionRepository struct {
	mock.Mock
}

type MockSubscriptionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubscriptionRepository) EXPECT() *MockSubscriptionRepository_Expecter {
	return &MockSubscriptionRepository_Expecter{mock: &_m.Mock}
}

// DeleteById provides a mock function for the type MockSubscriptionRepository
func (_mock *MockSubscriptionRepository) DeleteById(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, n int32) error {
	ret := _mock.Called(context1, sQLExecutor, n)

	if len(ret) == 0 {
		panic("no return value specified for DeleteById")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlutil.SQLExecutor, int32) error); ok {
		r0 = returnFunc(context1, sQLExecutor, n)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSubscriptionRepository_DeleteById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteById'
type MockSubscriptionRepository_DeleteById_Call struct {
	*mock.Call
}

// DeleteById is a helper method to define mock.On call
//   - context1 context.Context
//   - sQLExecutor sqlutil.SQLExecutor
//   - n int32
func (_e *MockSubscriptionRepository_Expecter) DeleteById(context1 interface{}, sQLExecutor interface{}, n interface{}) *MockSubscriptionRepository_DeleteById_Call {
	return &MockSubscriptionRepository_DeleteById_Call{Call: _e.mock.On("DeleteById", context1, sQLExecutor, n)}
}

func (_c *MockSubscriptionRepository_DeleteById_Call) Run(run func(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, n int32)) *MockSubscriptionRepository_DeleteById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlutil.SQLExecutor
		if args[1] != nil {
			arg1 = args[1].(sqlutil.SQLExecutor)
		}
		var arg2 int32
		if args[2] != nil {
			arg2 = args[2].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSubscriptionRepository_DeleteById_Call) Return(err error) *MockSubscriptionRepository_DeleteById_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSubscriptionRepository_DeleteById_Call) RunAndReturn(run func(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, n int32) error) *MockSubscriptionRepository_DeleteById_Call {
	_c.Call.Return(run)
	return _c
}

// FindById provides a mock function for the type MockSubscriptionRepository
func (_mock *MockSubscriptionRepository) FindById(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, n int32) (*model.Subscription, error) {
	ret := _mock.Called(context1, sQLExecutor, n)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 *model.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlutil.SQLExecutor, int32) (*model.Subscription, error)); ok {
		return returnFunc(context1, sQLExecutor, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlutil.SQLExecutor, int32) *model.Subscription); ok {
		r0 = returnFunc(context1, sQLExecutor, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlutil.SQLExecutor, int32) error); ok {
		r1 = returnFunc(context1, sQLExecutor, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubscriptionRepository_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type MockSubscriptionRepository_FindById_Call struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - context1 context.Context
//   - sQLExecutor sqlutil.SQLExecutor
//   - n int32
func (_e *MockSubscriptionRepository_Expecter) FindById(context1 interface{}, sQLExecutor interface{}, n interface{}) *MockSubscriptionRepository_FindById_Call {
	return &MockSubscriptionRepository_FindById_Call{Call: _e.mock.On("FindById", context1, sQLExecutor, n)}
}

func (_c *MockSubscriptionRepository_FindById_Call) Run(run func(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, n int32)) *MockSubscriptionRepository_FindById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlutil.SQLExecutor
		if args[1] != nil {
			arg1 = args[1].(sqlutil.SQLExecutor)
		}
		var arg2 int32
		if args[2] != nil {
			arg2 = args[2].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSubscriptionRepository_FindById_Call) Return(subscription *model.Subscription, err error) *MockSubscriptionRepository_FindById_Call {
	_c.Call.Return(subscription, err)
	return _c
}

func (_c *MockSubscriptionRepository_FindById_Call) RunAndReturn(run func(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, n int32) (*model.Subscription, error)) *MockSubscriptionRepository_FindById_Call {
	_c.Call.Return(run)
	return _c
}

// FindBySubscriberIdAndLocationName provides a mock function for the type MockSubscriptionRepository
func (_mock *MockSubscriptionRepository) FindBySubscriberIdAndLocationName(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, n int32, s string) (*model.Subscription, error) {
	ret := _mock.Called(context1, sQLExecutor, n, s)

	if len(ret) == 0 {
		panic("no return value specified for FindBySubscriberIdAndLocationName")
	}

	var r0 *model.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlutil.SQLExecutor, int32, string) (*model.Subscription, error)); ok {
		return returnFunc(context1, sQLExecutor, n, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlutil.SQLExecutor, int32, string) *model.Subscription); ok {
		r0 = returnFunc(context1, sQLExecutor, n, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlutil.SQLExecutor, int32, string) error); ok {
		r1 = returnFunc(context1, sQLExecutor, n, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubscriptionRepository_FindBySubscriberIdAndLocationName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySubscriberIdAndLocationName'
type MockSubscriptionRepository_FindBySubscriberIdAndLocationName_Call struct {
	*mock.Call
}

// FindBySubscriberIdAndLocationName is a helper method to define mock.On call
//   - context1 context.Context
//   - sQLExecutor sqlutil.SQLExecutor
//   - n int32
//   - s string
func (_e *MockSubscriptionRepository_Expecter) FindBySubscriberIdAndLocationName(context1 interface{}, sQLExecutor interface{}, n interface{}, s interface{}) *MockSubscriptionRepository_FindBySubscriberIdAndLocationName_Call {
	return &MockSubscriptionRepository_FindBySubscriberIdAndLocationName_Call{Call: _e.mock.On("FindBySubscriberIdAndLocationName", context1, sQLExecutor, n, s)}
}

func (_c *MockSubscriptionRepository_FindBySubscriberIdAndLocationName_Call) Run(run func(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, n int32, s string)) *MockSubscriptionRepository_FindBySubscriberIdAndLocationName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlutil.SQLExecutor
		if args[1] != nil {
			arg1 = args[1].(sqlutil.SQLExecutor)
		}
		var arg2 int32
		if args[2] != nil {
			arg2 = args[2].(int32)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSubscriptionRepository_FindBySubscriberIdAndLocationName_Call) Return(subscription *model.Subscription, err error) *MockSubscriptionRepository_FindBySubscriberIdAndLocationName_Call {
	_c.Call.Return(subscription, err)
	return _c
}

func (_c *MockSubscriptionRepository_FindBySubscriberIdAndLocationName_Call) RunAndReturn(run func(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, n int32, s string) (*model.Subscription, error)) *MockSubscriptionRepository_FindBySubscriberIdAndLocationName_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockSubscriptionRepository
func (_mock *MockSubscriptionRepository) Save(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, subscription *model.Subscription) (int32, error) {
	ret := _mock.Called(context1, sQLExecutor, subscription)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 int32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlutil.SQLExecutor, *model.Subscription) (int32, error)); ok {
		return returnFunc(context1, sQLExecutor, subscription)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlutil.SQLExecutor, *model.Subscription) int32); ok {
		r0 = returnFunc(context1, sQLExecutor, subscription)
	} else {
		r0 = ret.Get(0).(int32)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlutil.SQLExecutor, *model.Subscription) error); ok {
		r1 = returnFunc(context1, sQLExecutor, subscription)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubscriptionRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockSubscriptionRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - context1 context.Context
//   - sQLExecutor sqlutil.SQLExecutor
//   - subscription *model.Subscription
func (_e *MockSubscriptionRepository_Expecter) Save(context1 interface{}, sQLExecutor interface{}, subscription interface{}) *MockSubscriptionRepository_Save_Call {
	return &MockSubscriptionRepository_Save_Call{Call: _e.mock.On("Save", context1, sQLExecutor, subscription)}
}

func (_c *MockSubscriptionRepository_Save_Call) Run(run func(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, subscription *model.Subscription)) *MockSubscriptionRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlutil.SQLExecutor
		if args[1] != nil {
			arg1 = args[1].(sqlutil.SQLExecutor)
		}
		var arg2 *model.Subscription
		if args[2] != nil {
			arg2 = args[2].(*model.Subscription)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSubscriptionRepository_Save_Call) Return(n int32, err error) *MockSubscriptionRepository_Save_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSubscriptionRepository_Save_Call) RunAndReturn(run func(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, subscription *model.Subscription) (int32, error)) *MockSubscriptionRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockSubscriptionRepository
func (_mock *MockSubscriptionRepository) Update(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, subscription *model.Subscription) (*model.Subscription, error) {
	ret := _mock.Called(context1, sQLExecutor, subscription)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlutil.SQLExecutor, *model.Subscription) (*model.Subscription, error)); ok {
		return returnFunc(context1, sQLExecutor, subscription)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlutil.SQLExecutor, *model.Subscription) *model.Subscription); ok {
		r0 = returnFunc(context1, sQLExecutor, subscription)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlutil.SQLExecutor, *model.Subscription) error); ok {
		r1 = returnFunc(context1, sQLExecutor, subscription)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubscriptionRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSubscriptionRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - context1 context.Context
//   - sQLExecutor sqlutil.SQLExecutor
//   - subscription *model.Subscription
func (_e *MockSubscriptionRepository_Expecter) Update(context1 interface{}, sQLExecutor interface{}, subscription interface{}) *MockSubscriptionRepository_Update_Call {
	return &MockSubscriptionRepository_Update_Call{Call: _e.mock.On("Update", context1, sQLExecutor, subscription)}
}

func (_c *MockSubscriptionRepository_Update_Call) Run(run func(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, subscription *model.Subscription)) *MockSubscriptionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlutil.SQLExecutor
		if args[1] != nil {
			arg1 = args[1].(sqlutil.SQLExecutor)
		}
		var arg2 *model.Subscription
		if args[2] != nil {
			arg2 = args[2].(*model.Subscription)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSubscriptionRepository_Update_Call) Return(subscription1 *model.Subscription, err error) *MockSubscriptionRepository_Update_Call {
	_c.Call.Return(subscription1, err)
	return _c
}

func (_c *MockSubscriptionRepository_Update_Call) RunAndReturn(run func(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, subscription *model.Subscription) (*model.Subscription, error)) *MockSubscriptionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenRepository creates a new instance of MockTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenRepository {
	mock := &MockTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenRepository is an autogenerated mock type for the TokenRepository type
type MockTokenRepository struct {
	mock.Mock
}

type MockTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenRepository) EXPECT() *MockTokenRepository_Expecter {
	return &MockTokenRepository_Expecter{mock: &_m.Mock}
}

// FindByToken provides a mock function for the type MockTokenRepository
func (_mock *MockTokenRepository) FindByToken(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, s string) (*model.Token, error) {
	ret := _mock.Called(context1, sQLExecutor, s)

	if len(ret) == 0 {
		panic("no return value specified for FindByToken")
	}

	var r0 *model.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlutil.SQLExecutor, string) (*model.Token, error)); ok {
		return returnFunc(context1, sQLExecutor, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlutil.SQLExecutor, string) *model.Token); ok {
		r0 = returnFunc(context1, sQLExecutor, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlutil.SQLExecutor, string) error); ok {
		r1 = returnFunc(context1, sQLExecutor, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenRepository_FindByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByToken'
type MockTokenRepository_FindByToken_Call struct {
	*mock.Call
}

// FindByToken is a helper method to define mock.On call
//   - context1 context.Context
//   - sQLExecutor sqlutil.SQLExecutor
//   - s string
func (_e *MockTokenRepository_Expecter) FindByToken(context1 interface{}, sQLExecutor interface{}, s interface{}) *MockTokenRepository_FindByToken_Call {
	return &MockTokenRepository_FindByToken_Call{Call: _e.mock.On("FindByToken", context1, sQLExecutor, s)}
}

func (_c *MockTokenRepository_FindByToken_Call) Run(run func(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, s string)) *MockTokenRepository_FindByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlutil.SQLExecutor
		if args[1] != nil {
			arg1 = args[1].(sqlutil.SQLExecutor)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTokenRepository_FindByToken_Call) Return(token *model.Token, err error) *MockTokenRepository_FindByToken_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockTokenRepository_FindByToken_Call) RunAndReturn(run func(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, s string) (*model.Token, error)) *MockTokenRepository_FindByToken_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockTokenRepository
func (_mock *MockTokenRepository) Save(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, token *model.Token) error {
	ret := _mock.Called(context1, sQLExecutor, token)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlutil.SQLExecutor, *model.Token) error); ok {
		r0 = returnFunc(context1, sQLExecutor, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockTokenRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - context1 context.Context
//   - sQLExecutor sqlutil.SQLExecutor
//   - token *model.Token
func (_e *MockTokenRepository_Expecter) Save(context1 interface{}, sQLExecutor interface{}, token interface{}) *MockTokenRepository_Save_Call {
	return &MockTokenRepository_Save_Call{Call: _e.mock.On("Save", context1, sQLExecutor, token)}
}

func (_c *MockTokenRepository_Save_Call) Run(run func(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, token *model.Token)) *MockTokenRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlutil.SQLExecutor
		if args[1] != nil {
			arg1 = args[1].(sqlutil.SQLExecutor)
		}
		var arg2 *model.Token
		if args[2] != nil {
			arg2 = args[2].(*model.Token)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTokenRepository_Save_Call) Return(err error) *MockTokenRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenRepository_Save_Call) RunAndReturn(run func(context1 context.Context, sQLExecutor sqlutil.SQLExecutor, token *model.Token) error) *MockTokenRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEmailSender creates a new instance of MockEmailSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailSender {
	mock := &MockEmailSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEmailSender is an autogenerated mock type for the EmailSender type
type MockEmailSender struct {
	mock.Mock
}

type MockEmailSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmailSender) EXPECT() *MockEmailSender_Expecter {
	return &MockEmailSender_Expecter{mock: &_m.Mock}
}

// Send provides a mock function for the type MockEmailSender
func (_mock *MockEmailSender) Send(context1 context.Context, simpleEmail dto.SimpleEmail) error {
	ret := _mock.Called(context1, simpleEmail)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.SimpleEmail) error); ok {
		r0 = returnFunc(context1, simpleEmail)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmailSender_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockEmailSender_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - context1 context.Context
//   - simpleEmail dto.SimpleEmail
func (_e *MockEmailSender_Expecter) Send(context1 interface{}, simpleEmail interface{}) *MockEmailSender_Send_Call {
	return &MockEmailSender_Send_Call{Call: _e.mock.On("Send", context1, simpleEmail)}
}

func (_c *MockEmailSender_Send_Call) Run(run func(context1 context.Context, simpleEmail dto.SimpleEmail)) *MockEmailSender_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.SimpleEmail
		if args[1] != nil {
			arg1 = args[1].(dto.SimpleEmail)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEmailSender_Send_Call) Return(err error) *MockEmailSender_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmailSender_Send_Call) RunAndReturn(run func(context1 context.Context, simpleEmail dto.SimpleEmail) error) *MockEmailSender_Send_Call {
	_c.Call.Return(run)
	return _c
}
