name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'

      - name: Lint weather-upd-subscription-srv
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
          working-directory: ./weather-upd-subscription-srv

      - name: Lint notification-srv
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
          working-directory: ./notification-srv


  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'

      - name: Install dependencies
        run: go mod download

      - name: Run unit tests (weather-upd-subscription-srv)
        run: go test -v ./weather-upd-subscription-srv/...

      - name: Run integration tests (weather-upd-subscription-srv)
        run: go test -v --tags=integration ./weather-upd-subscription-srv/...

      - name: Run unit tests (notification-srv)
        run: go test -v ./notification-srv/...

      - name: Run integration tests (notification-srv)
        run: go test -v --tags=integration ./notification-srv/...